### ISSUE TITLE
Problem running tests

### ISSUE THREAD

**Issue by Download** [tleunen/react-mdl#325]
I am trying to run the tests on the V2 branch, because I wanted to get my feet wet trying to help out with the Textfield V2 task. However I can't run the tests. There is some error.

I am not proficient with 'Istanbul' and I'm running on Windows, so this may be just 'user error'. If that is the case then sorry, but I've found that many project's builds just don't work on Windows so I check with you before trying to fix it myself.  Should it work on Windows?

I think the problem is with `$npm_package_config_istanbul`... On Windows you should use `%npm_package_config_istanbul%` I think?

```sh
c:\ws\react-mdl>npm install
supports-color@3.1.2 node_modules\istanbul\node_modules\supports-color -> node_modules\istanbul-lib-report\node_modules\supports-color
react-mdl@1.5.3 c:\ws\react-mdl
├─┬ chai@3.5.0
│ ├── assertion-error@1.0.2
│ ├─┬ deep-eql@0.1.3
│ │ └── type-detect@0.1.1
│ └── type-detect@1.0.0
├─┬ chai-enzyme@0.4.2
│ └─┬ html@0.0.10
│   └─┬ glob@3.2.11
│     └─┬ minimatch@0.3.0
│       └── lru-cache@2.7.3
├─┬ cross-env@1.0.7
│ └─┬ cross-spawn-async@2.0.0
│   └── lru-cache@2.7.3
├─┬ enzyme@2.3.0
│ ├─┬ cheerio@0.20.0
│ │ ├─┬ css-select@1.2.0
│ │ │ ├── boolbase@1.0.0
│ │ │ ├── css-what@2.1.0
│ │ │ ├── domutils@1.5.1
│ │ │ └── nth-check@1.0.1
│ │ ├─┬ dom-serializer@0.1.0
│ │ │ └── domelementtype@1.1.3
│ │ ├─┬ htmlparser2@3.8.3
│ │ │ ├── domelementtype@1.3.0
│ │ │ ├── domhandler@2.3.0
│ │ │ ├── entities@1.0.0
│ │ │ └── readable-stream@1.1.14
│ │ ├─┬ jsdom@7.2.2
│ │ │ ├── acorn@2.7.0
│ │ │ ├── webidl-conversions@2.0.1
│ │ │ └── whatwg-url-compat@0.6.5
│ │ └── lodash@4.13.1
│ ├── is-subset@0.1.1
│ ├── lodash@4.13.1
│ ├── object-is@1.0.1
│ ├── object.assign@4.0.3
│ └── object.values@1.0.3
├─┬ eslint@2.8.0
│ └─┬ espree@3.1.3
│   └─┬ acorn-jsx@2.0.1
│     └── acorn@2.7.0
├── eslint-config-airbnb@7.0.0
├── eslint-plugin-jsx-a11y@0.6.2
├─┬ gatsby@0.9.3
│ ├─┬ css-loader@0.23.1
│ │ └─┬ postcss@5.0.19
│ │   └── supports-color@3.1.2
│ ├─┬ node-libs-browser@0.5.3
│ │ ├── readable-stream@1.1.14
│ │ └─┬ stream-browserify@1.0.0
│ │   └── readable-stream@1.1.14
│ └─┬ node-sass@3.4.2
│   ├─┬ gaze@0.5.2
│   │ └─┬ globule@0.1.0
│   │   └─┬ minimatch@0.2.14
│   │     └── lru-cache@2.7.3
│   └─┬ node-gyp@3.3.1
│     └─┬ minimatch@1.0.0
│       └── lru-cache@2.7.3
├─┬ isparta@4.0.0
│ └─┬ istanbul@0.4.3
│   └── supports-color@3.1.2
├─┬ istanbul@1.0.0-alpha.2
│ └─┬ istanbul-api@1.0.0-alpha.13
│   ├── istanbul-lib-coverage@1.0.0-alpha.4
│   ├─┬ istanbul-lib-hook@1.0.0-alpha.4
│   │ └── append-transform@0.3.0
│   ├── istanbul-lib-instrument@1.0.0-alpha.6
│   ├─┬ istanbul-lib-report@1.0.0-alpha.3
│   │ ├── path-parse@1.0.5
│   │ └── supports-color@3.1.2
│   ├── istanbul-lib-source-maps@1.0.0-alpha.10
│   └── istanbul-reports@1.0.0-alpha.4
├─┬ jsdom@8.5.0
│ ├── abab@1.0.3
│ ├── acorn@2.7.0
│ ├─┬ acorn-globals@1.0.9
│ │ └── acorn@2.7.0
│ ├── array-equal@1.0.0
│ ├── cssom@0.3.1
│ ├── cssstyle@0.2.36
│ ├── nwmatcher@1.3.8
│ ├── parse5@1.5.1
│ ├── symbol-tree@3.1.4
│ ├── webidl-conversions@3.0.1
│ ├─┬ whatwg-url@2.0.1
│ │ ├── tr46@0.0.3
│ │ └── webidl-conversions@3.0.1
│ └── xml-name-validator@2.0.1
├─┬ karma-coverage@0.5.5
│ └─┬ istanbul@0.4.3
│   └── supports-color@3.1.2
├─┬ mocha@2.4.5
│ └─┬ glob@3.2.3
│   └─┬ minimatch@0.2.14
│     └── lru-cache@2.7.3
├─┬ react@15.1.0
│ ├─┬ fbjs@0.8.3
│ │ └── immutable@3.8.1
│ └── object-assign@4.1.0
├── react-addons-test-utils@15.1.0
├── react-dom@15.1.0
├─┬ webpack@1.13.0
│ └── supports-color@3.1.2
└─┬ webpack-dev-server@1.14.1
  └── supports-color@3.1.2

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12

c:\ws\react-mdl>npm run test

> react-mdl@1.5.3 pretest c:\ws\react-mdl
> npm run lint


> react-mdl@1.5.3 lint c:\ws\react-mdl
> eslint docs src scripts


> react-mdl@1.5.3 test c:\ws\react-mdl
> npm run test:react:14 && npm run test:react:15


> react-mdl@1.5.3 test:react:14 c:\ws\react-mdl
> npm run react:14 && npm run test:suite


> react-mdl@1.5.3 react:14 c:\ws\react-mdl
> npm run react:clean && npm i react@0.14 react-dom@0.14 react-addons-test-utils@0.14


> react-mdl@1.5.3 react:clean c:\ws\react-mdl
> rimraf node_modules/react node_modules/react-dom node_modules/react-addons-test-utils

react-mdl@1.5.3 c:\ws\react-mdl
├─┬ gatsby@0.9.3
│ ├── react@0.14.8
│ └── react-dom@0.14.8
├── react@0.14.8  extraneous
├── react-addons-test-utils@0.14.8  extraneous
└── react-dom@0.14.8  extraneous

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12

> react-mdl@1.5.3 test:suite c:\ws\react-mdl
> istanbul cover $npm_package_config_istanbul _mocha -- $npm_package_config_mocha

Unable to resolve file [$npm_package_config_istanbul]
Try "istanbul help" for usage

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Frank\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:suite"
npm ERR! node v5.4.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! react-mdl@1.5.3 test:suite: `istanbul cover $npm_package_config_istanbul _mocha -- $npm_package_config_mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-mdl@1.5.3 test:suite script 'istanbul cover $npm_package_config_istanbul _mocha -- $npm_package_config_mocha'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-mdl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     istanbul cover $npm_package_config_istanbul _mocha -- $npm_package_config_mocha
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-mdl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-mdl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\ws\react-mdl\npm-debug.log

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Frank\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:react:14"
npm ERR! node v5.4.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! react-mdl@1.5.3 test:react:14: `npm run react:14 && npm run test:suite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-mdl@1.5.3 test:react:14 script 'npm run react:14 && npm run test:suite'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-mdl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run react:14 && npm run test:suite
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-mdl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-mdl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\ws\react-mdl\npm-debug.log

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Frank\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
npm ERR! node v5.4.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! react-mdl@1.5.3 test: `npm run test:react:14 && npm run test:react:15`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-mdl@1.5.3 test script 'npm run test:react:14 && npm run test:react:15'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-mdl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run test:react:14 && npm run test:react:15
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-mdl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-mdl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\ws\react-mdl\npm-debug.log
```

**Comment by Download** [comment]
###npm-debug.log

```sh
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Frank\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test' ]
2 info using npm@3.5.3
3 info using node@v5.4.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle react-mdl@1.5.3~pretest: react-mdl@1.5.3
6 verbose lifecycle react-mdl@1.5.3~pretest: unsafe-perm in lifecycle true
7 verbose lifecycle react-mdl@1.5.3~pretest: PATH: C:\Users\Frank\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;c:\ws\react-mdl\node_modules\.bin;C:\Program Files (x86)\Oculus\Support\oculus-runtime;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\MySQL\MySQL Server 5.5\bin;C:\p4merge\DVCS\;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\maven\v3.3.9\bin;C:\Program Files (x86)\GNU\GnuPG\pub;C:\Users\Frank\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\D\v2.070.2\dmd2\windows\bin;C:\Program Files (x86)\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Program Files\EmEditor;C:\Users\Frank\AppData\Local\Programs\Python\Python35\Scripts\;C:\Users\Frank\AppData\Local\Programs\Python\Python35\;C:\Ruby193\bin;C:\Users\Frank\AppData\Roaming\npm;C:\Program Files (x86)\Jar2Exe Wizard\
8 verbose lifecycle react-mdl@1.5.3~pretest: CWD: c:\ws\react-mdl
9 silly lifecycle react-mdl@1.5.3~pretest: Args: [ '/d /s /c', 'npm run lint' ]
10 silly lifecycle react-mdl@1.5.3~pretest: Returned: code: 0  signal: null
11 info lifecycle react-mdl@1.5.3~test: react-mdl@1.5.3
12 verbose lifecycle react-mdl@1.5.3~test: unsafe-perm in lifecycle true
13 verbose lifecycle react-mdl@1.5.3~test: PATH: C:\Users\Frank\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;c:\ws\react-mdl\node_modules\.bin;C:\Program Files (x86)\Oculus\Support\oculus-runtime;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\MySQL\MySQL Server 5.5\bin;C:\p4merge\DVCS\;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\maven\v3.3.9\bin;C:\Program Files (x86)\GNU\GnuPG\pub;C:\Users\Frank\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\D\v2.070.2\dmd2\windows\bin;C:\Program Files (x86)\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Program Files\EmEditor;C:\Users\Frank\AppData\Local\Programs\Python\Python35\Scripts\;C:\Users\Frank\AppData\Local\Programs\Python\Python35\;C:\Ruby193\bin;C:\Users\Frank\AppData\Roaming\npm;C:\Program Files (x86)\Jar2Exe Wizard\
14 verbose lifecycle react-mdl@1.5.3~test: CWD: c:\ws\react-mdl
15 silly lifecycle react-mdl@1.5.3~test: Args: [ '/d /s /c', 'npm run test:react:14 && npm run test:react:15' ]
16 silly lifecycle react-mdl@1.5.3~test: Returned: code: 1  signal: null
17 info lifecycle react-mdl@1.5.3~test: Failed to exec test script
18 verbose stack Error: react-mdl@1.5.3 test: `npm run test:react:14 && npm run test:react:15`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (C:\Users\Frank\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:232:16)
18 verbose stack     at emitTwo (events.js:87:13)
18 verbose stack     at EventEmitter.emit (events.js:172:7)
18 verbose stack     at ChildProcess.<anonymous> (C:\Users\Frank\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
18 verbose stack     at emitTwo (events.js:87:13)
18 verbose stack     at ChildProcess.emit (events.js:172:7)
18 verbose stack     at maybeClose (internal/child_process.js:821:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
19 verbose pkgid react-mdl@1.5.3
20 verbose cwd c:\ws\react-mdl
21 error Windows_NT 10.0.10586
22 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Frank\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
23 error node v5.4.0
24 error npm  v3.5.3
25 error code ELIFECYCLE
26 error react-mdl@1.5.3 test: `npm run test:react:14 && npm run test:react:15`
26 error Exit status 1
27 error Failed at the react-mdl@1.5.3 test script 'npm run test:react:14 && npm run test:react:15'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the react-mdl package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     npm run test:react:14 && npm run test:react:15
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs react-mdl
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls react-mdl
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]
```

**Comment by tleunen** [comment]
Thanks @Download, I'll take a look tonight to resolve this issue. I've been busy like hell this past few weeks but I'll try to come back to this development, especially since the MDL team started development on their v2 as well. I have to see how we can use/reuse their stuff.
